name: Deploy Jekyll site to Pages

on:
  push:
    branches: [main]  # You can change this to a specific branch (without the $)
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest  # Use the self-hosted runner here
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch whole history for jekyll-last-modified-at plugin

      # Install Ruby manually using ruby-build
      - name: Install Ruby
        run: |
          curl -sSL https://github.com/rbenv/ruby-build/archive/master.tar.gz | tar -xz
          cd ruby-build-master
          sudo PREFIX=/opt/hostedtoolcache/Ruby ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
        continue-on-error: false  # Ensure this step fails if Ruby installation doesn't succeed

      # Ensure Ruby and Bundler are installed
      - name: Install Bundler and Jekyll
        run: |
          /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/gem install bundler
          /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/gem install jekyll

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04-x64
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
